# Generated by Django 2.1.5 on 2019-01-30 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='last_updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='weather',
            name='url',
            field=models.URLField(default='https://pogoda.interia.pl/'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind',
            field=models.FloatField(default=0),
        ),
    ]
