# Generated by Django 2.2.5 on 2019-11-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20190130_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='wind',
        ),
        migrations.AlterField(
            model_name='weather',
            name='url',
            field=models.URLField(),
        ),
    ]
